### ISSUE TITLE
Upgrade to JupyterLab 2.0.0

### ISSUE THREAD

**Issue by codypiersall** [wallneradam/jupyterlab-trailing-space-remover#2]
First off, thanks for making this extension.  I love it!

JupyterLab 2.0.0 had some breaking changes which cause this extension not to work.  The biggest difference is that phosphorjs got renamed, according to the [migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#upgrading-library-versions).

I was hoping to upgrade to 2.0.0 and put in a PR instead of open an issue, but I failed to get this extension to build, probably because I have no idea how developing a JavaScript application works.  I ended up with 650 typescript errors from the bowels of JupyterLab core JS files (` An accessor cannot be declared in an ambient context.`) which I assume are because I set things up incorrectly.

**Comment by codypiersall** [comment]
Ah, it turns out the errors were because the version of TypeScript needed to be upgraded. I will have a PR shortly.

**Comment by wallneradam** [comment]
Thanks again for your help.
